
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.ComponentModel
Imports System.Data.EntityClient
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq
Imports System.Runtime.Serialization
Imports System.Xml.Serialization


<Assembly: EdmSchemaAttribute("08ce02ac-10d4-4c80-b3ff-ec69a356a742")>
#Region "EDM Relationship Metadata"
<Assembly: EdmRelationshipAttribute("SealSuiteDBModel", "FK_tblProcess_UserRole_tblRole", "tblRole", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(tblRole), "tblProcess_UserRole", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(tblProcess_UserRole), True)>
<Assembly: EdmRelationshipAttribute("SealSuiteDBModel", "FK_tblProcess_UserRole_tblUser", "tblUser", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(tblUser), "tblProcess_UserRole", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(tblProcess_UserRole), True)>
<Assembly: EdmRelationshipAttribute("SealSuiteDBModel", "FK_tblSealUserRole_tblRole", "tblRole", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(tblRole), "tblTest_UserRole", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(tblTest_UserRole), True)>
<Assembly: EdmRelationshipAttribute("SealSuiteDBModel", "FK_tblSealUserRole_tblSealUser", "tblUser", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(tblUser), "tblTest_UserRole", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(tblTest_UserRole), True)>
<Assembly: EdmRelationshipAttribute("SealSuiteDBModel", "FK_tblSealUser_tblTitle", "tblTitle", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(tblTitle), "tblUser", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(tblUser), True)>

#End Region

#Region "Contexts"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
Public Partial Class SealSuiteDBEntities
    Inherits ObjectContext

    #Region "Constructors"

    ''' <summary>
    ''' Initializes a new SealSuiteDBEntities object using the connection string found in the 'SealSuiteDBEntities' section of the application configuration file.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=SealSuiteDBEntities", "SealSuiteDBEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new SealSuiteDBEntities object.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "SealSuiteDBEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new SealSuiteDBEntities object.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "SealSuiteDBEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    #End Region

    #Region "Partial Methods"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "ObjectSet Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property tblProcess_UserRole() As ObjectSet(Of tblProcess_UserRole)
        Get
            If (_tblProcess_UserRole Is Nothing) Then
                _tblProcess_UserRole = MyBase.CreateObjectSet(Of tblProcess_UserRole)("tblProcess_UserRole")
            End If
            Return _tblProcess_UserRole
        End Get
    End Property

    Private _tblProcess_UserRole As ObjectSet(Of tblProcess_UserRole)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property tblProgramDataFile() As ObjectSet(Of tblProgramDataFile)
        Get
            If (_tblProgramDataFile Is Nothing) Then
                _tblProgramDataFile = MyBase.CreateObjectSet(Of tblProgramDataFile)("tblProgramDataFile")
            End If
            Return _tblProgramDataFile
        End Get
    End Property

    Private _tblProgramDataFile As ObjectSet(Of tblProgramDataFile)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property tblRole() As ObjectSet(Of tblRole)
        Get
            If (_tblRole Is Nothing) Then
                _tblRole = MyBase.CreateObjectSet(Of tblRole)("tblRole")
            End If
            Return _tblRole
        End Get
    End Property

    Private _tblRole As ObjectSet(Of tblRole)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property tblTest_UserRole() As ObjectSet(Of tblTest_UserRole)
        Get
            If (_tblTest_UserRole Is Nothing) Then
                _tblTest_UserRole = MyBase.CreateObjectSet(Of tblTest_UserRole)("tblTest_UserRole")
            End If
            Return _tblTest_UserRole
        End Get
    End Property

    Private _tblTest_UserRole As ObjectSet(Of tblTest_UserRole)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property tblTitle() As ObjectSet(Of tblTitle)
        Get
            If (_tblTitle Is Nothing) Then
                _tblTitle = MyBase.CreateObjectSet(Of tblTitle)("tblTitle")
            End If
            Return _tblTitle
        End Get
    End Property

    Private _tblTitle As ObjectSet(Of tblTitle)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property tblUser() As ObjectSet(Of tblUser)
        Get
            If (_tblUser Is Nothing) Then
                _tblUser = MyBase.CreateObjectSet(Of tblUser)("tblUser")
            End If
            Return _tblUser
        End Get
    End Property

    Private _tblUser As ObjectSet(Of tblUser)

    #End Region

    #Region "AddTo Methods"

    ''' <summary>
    ''' Deprecated Method for adding a new object to the tblProcess_UserRole EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddTotblProcess_UserRole(ByVal tblProcess_UserRole As tblProcess_UserRole)
        MyBase.AddObject("tblProcess_UserRole", tblProcess_UserRole)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the tblProgramDataFile EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddTotblProgramDataFile(ByVal tblProgramDataFile As tblProgramDataFile)
        MyBase.AddObject("tblProgramDataFile", tblProgramDataFile)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the tblRole EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddTotblRole(ByVal tblRole As tblRole)
        MyBase.AddObject("tblRole", tblRole)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the tblTest_UserRole EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddTotblTest_UserRole(ByVal tblTest_UserRole As tblTest_UserRole)
        MyBase.AddObject("tblTest_UserRole", tblTest_UserRole)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the tblTitle EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddTotblTitle(ByVal tblTitle As tblTitle)
        MyBase.AddObject("tblTitle", tblTitle)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the tblUser EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddTotblUser(ByVal tblUser As tblUser)
        MyBase.AddObject("tblUser", tblUser)
    End Sub

    #End Region

End Class

#End Region

#Region "Entities"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="SealSuiteDBModel", Name:="tblProcess_UserRole")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class tblProcess_UserRole
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new tblProcess_UserRole object.
    ''' </summary>
    ''' <param name="fldID">Initial value of the fldID property.</param>
    Public Shared Function CreatetblProcess_UserRole(fldID As Global.System.Decimal) As tblProcess_UserRole
        Dim tblProcess_UserRole as tblProcess_UserRole = New tblProcess_UserRole
        tblProcess_UserRole.fldID = fldID
        Return tblProcess_UserRole
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property fldID() As Global.System.Decimal
        Get
            Return _fldID
        End Get
        Set
            If (_fldID <> Value) Then
                OnfldIDChanging(value)
                ReportPropertyChanging("fldID")
                _fldID = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("fldID")
                OnfldIDChanged()
            End If
        End Set
    End Property

    Private _fldID As Global.System.Decimal
    Private Partial Sub OnfldIDChanging(value As Global.System.Decimal)
    End Sub

    Private Partial Sub OnfldIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property fldUserID() As Nullable(Of Global.System.Decimal)
        Get
            Return _fldUserID
        End Get
        Set
            OnfldUserIDChanging(value)
            ReportPropertyChanging("fldUserID")
            _fldUserID = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("fldUserID")
            OnfldUserIDChanged()
        End Set
    End Property

    Private _fldUserID As Nullable(Of Global.System.Decimal)
    Private Partial Sub OnfldUserIDChanging(value As Nullable(Of Global.System.Decimal))
    End Sub

    Private Partial Sub OnfldUserIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property fldRoleID() As Nullable(Of Global.System.Decimal)
        Get
            Return _fldRoleID
        End Get
        Set
            OnfldRoleIDChanging(value)
            ReportPropertyChanging("fldRoleID")
            _fldRoleID = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("fldRoleID")
            OnfldRoleIDChanged()
        End Set
    End Property

    Private _fldRoleID As Nullable(Of Global.System.Decimal)
    Private Partial Sub OnfldRoleIDChanging(value As Nullable(Of Global.System.Decimal))
    End Sub

    Private Partial Sub OnfldRoleIDChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("SealSuiteDBModel", "FK_tblProcess_UserRole_tblRole", "tblRole")>
    Public Property tblRole() As tblRole
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of tblRole)("SealSuiteDBModel.FK_tblProcess_UserRole_tblRole", "tblRole").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of tblRole)("SealSuiteDBModel.FK_tblProcess_UserRole_tblRole", "tblRole").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property tblRoleReference() As EntityReference(Of tblRole)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of tblRole)("SealSuiteDBModel.FK_tblProcess_UserRole_tblRole", "tblRole")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of tblRole)("SealSuiteDBModel.FK_tblProcess_UserRole_tblRole", "tblRole", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("SealSuiteDBModel", "FK_tblProcess_UserRole_tblUser", "tblUser")>
    Public Property tblUser() As tblUser
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of tblUser)("SealSuiteDBModel.FK_tblProcess_UserRole_tblUser", "tblUser").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of tblUser)("SealSuiteDBModel.FK_tblProcess_UserRole_tblUser", "tblUser").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property tblUserReference() As EntityReference(Of tblUser)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of tblUser)("SealSuiteDBModel.FK_tblProcess_UserRole_tblUser", "tblUser")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of tblUser)("SealSuiteDBModel.FK_tblProcess_UserRole_tblUser", "tblUser", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="SealSuiteDBModel", Name:="tblProgramDataFile")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class tblProgramDataFile
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new tblProgramDataFile object.
    ''' </summary>
    ''' <param name="fldID">Initial value of the fldID property.</param>
    Public Shared Function CreatetblProgramDataFile(fldID As Global.System.Decimal) As tblProgramDataFile
        Dim tblProgramDataFile as tblProgramDataFile = New tblProgramDataFile
        tblProgramDataFile.fldID = fldID
        Return tblProgramDataFile
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property fldID() As Global.System.Decimal
        Get
            Return _fldID
        End Get
        Set
            If (_fldID <> Value) Then
                OnfldIDChanging(value)
                ReportPropertyChanging("fldID")
                _fldID = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("fldID")
                OnfldIDChanged()
            End If
        End Set
    End Property

    Private _fldID As Global.System.Decimal
    Private Partial Sub OnfldIDChanging(value As Global.System.Decimal)
    End Sub

    Private Partial Sub OnfldIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property fldFileName_UserGroup() As Global.System.String
        Get
            Return _fldFileName_UserGroup
        End Get
        Set
            OnfldFileName_UserGroupChanging(value)
            ReportPropertyChanging("fldFileName_UserGroup")
            _fldFileName_UserGroup = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("fldFileName_UserGroup")
            OnfldFileName_UserGroupChanged()
        End Set
    End Property

    Private _fldFileName_UserGroup As Global.System.String
    Private Partial Sub OnfldFileName_UserGroupChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnfldFileName_UserGroupChanged()
    End Sub

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="SealSuiteDBModel", Name:="tblRole")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class tblRole
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new tblRole object.
    ''' </summary>
    ''' <param name="fldID">Initial value of the fldID property.</param>
    Public Shared Function CreatetblRole(fldID As Global.System.Decimal) As tblRole
        Dim tblRole as tblRole = New tblRole
        tblRole.fldID = fldID
        Return tblRole
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property fldID() As Global.System.Decimal
        Get
            Return _fldID
        End Get
        Set
            If (_fldID <> Value) Then
                OnfldIDChanging(value)
                ReportPropertyChanging("fldID")
                _fldID = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("fldID")
                OnfldIDChanged()
            End If
        End Set
    End Property

    Private _fldID As Global.System.Decimal
    Private Partial Sub OnfldIDChanging(value As Global.System.Decimal)
    End Sub

    Private Partial Sub OnfldIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property fldRole() As Global.System.String
        Get
            Return _fldRole
        End Get
        Set
            OnfldRoleChanging(value)
            ReportPropertyChanging("fldRole")
            _fldRole = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("fldRole")
            OnfldRoleChanged()
        End Set
    End Property

    Private _fldRole As Global.System.String
    Private Partial Sub OnfldRoleChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnfldRoleChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property fldIsSuperRole() As Nullable(Of Global.System.Boolean)
        Get
            Return _fldIsSuperRole
        End Get
        Set
            OnfldIsSuperRoleChanging(value)
            ReportPropertyChanging("fldIsSuperRole")
            _fldIsSuperRole = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("fldIsSuperRole")
            OnfldIsSuperRoleChanged()
        End Set
    End Property

    Private _fldIsSuperRole As Nullable(Of Global.System.Boolean)
    Private Partial Sub OnfldIsSuperRoleChanging(value As Nullable(Of Global.System.Boolean))
    End Sub

    Private Partial Sub OnfldIsSuperRoleChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("SealSuiteDBModel", "FK_tblProcess_UserRole_tblRole", "tblProcess_UserRole")>
     Public Property tblProcess_UserRole() As EntityCollection(Of tblProcess_UserRole)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of tblProcess_UserRole)("SealSuiteDBModel.FK_tblProcess_UserRole_tblRole", "tblProcess_UserRole")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of tblProcess_UserRole)("SealSuiteDBModel.FK_tblProcess_UserRole_tblRole", "tblProcess_UserRole", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("SealSuiteDBModel", "FK_tblSealUserRole_tblRole", "tblTest_UserRole")>
     Public Property tblTest_UserRole() As EntityCollection(Of tblTest_UserRole)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of tblTest_UserRole)("SealSuiteDBModel.FK_tblSealUserRole_tblRole", "tblTest_UserRole")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of tblTest_UserRole)("SealSuiteDBModel.FK_tblSealUserRole_tblRole", "tblTest_UserRole", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="SealSuiteDBModel", Name:="tblTest_UserRole")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class tblTest_UserRole
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new tblTest_UserRole object.
    ''' </summary>
    ''' <param name="fldID">Initial value of the fldID property.</param>
    Public Shared Function CreatetblTest_UserRole(fldID As Global.System.Decimal) As tblTest_UserRole
        Dim tblTest_UserRole as tblTest_UserRole = New tblTest_UserRole
        tblTest_UserRole.fldID = fldID
        Return tblTest_UserRole
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property fldID() As Global.System.Decimal
        Get
            Return _fldID
        End Get
        Set
            If (_fldID <> Value) Then
                OnfldIDChanging(value)
                ReportPropertyChanging("fldID")
                _fldID = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("fldID")
                OnfldIDChanged()
            End If
        End Set
    End Property

    Private _fldID As Global.System.Decimal
    Private Partial Sub OnfldIDChanging(value As Global.System.Decimal)
    End Sub

    Private Partial Sub OnfldIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property fldUserID() As Nullable(Of Global.System.Decimal)
        Get
            Return _fldUserID
        End Get
        Set
            OnfldUserIDChanging(value)
            ReportPropertyChanging("fldUserID")
            _fldUserID = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("fldUserID")
            OnfldUserIDChanged()
        End Set
    End Property

    Private _fldUserID As Nullable(Of Global.System.Decimal)
    Private Partial Sub OnfldUserIDChanging(value As Nullable(Of Global.System.Decimal))
    End Sub

    Private Partial Sub OnfldUserIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property fldRoleID() As Nullable(Of Global.System.Decimal)
        Get
            Return _fldRoleID
        End Get
        Set
            OnfldRoleIDChanging(value)
            ReportPropertyChanging("fldRoleID")
            _fldRoleID = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("fldRoleID")
            OnfldRoleIDChanged()
        End Set
    End Property

    Private _fldRoleID As Nullable(Of Global.System.Decimal)
    Private Partial Sub OnfldRoleIDChanging(value As Nullable(Of Global.System.Decimal))
    End Sub

    Private Partial Sub OnfldRoleIDChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("SealSuiteDBModel", "FK_tblSealUserRole_tblRole", "tblRole")>
    Public Property tblRole() As tblRole
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of tblRole)("SealSuiteDBModel.FK_tblSealUserRole_tblRole", "tblRole").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of tblRole)("SealSuiteDBModel.FK_tblSealUserRole_tblRole", "tblRole").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property tblRoleReference() As EntityReference(Of tblRole)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of tblRole)("SealSuiteDBModel.FK_tblSealUserRole_tblRole", "tblRole")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of tblRole)("SealSuiteDBModel.FK_tblSealUserRole_tblRole", "tblRole", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("SealSuiteDBModel", "FK_tblSealUserRole_tblSealUser", "tblUser")>
    Public Property tblUser() As tblUser
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of tblUser)("SealSuiteDBModel.FK_tblSealUserRole_tblSealUser", "tblUser").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of tblUser)("SealSuiteDBModel.FK_tblSealUserRole_tblSealUser", "tblUser").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property tblUserReference() As EntityReference(Of tblUser)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of tblUser)("SealSuiteDBModel.FK_tblSealUserRole_tblSealUser", "tblUser")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of tblUser)("SealSuiteDBModel.FK_tblSealUserRole_tblSealUser", "tblUser", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="SealSuiteDBModel", Name:="tblTitle")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class tblTitle
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new tblTitle object.
    ''' </summary>
    ''' <param name="fldID">Initial value of the fldID property.</param>
    Public Shared Function CreatetblTitle(fldID As Global.System.Decimal) As tblTitle
        Dim tblTitle as tblTitle = New tblTitle
        tblTitle.fldID = fldID
        Return tblTitle
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property fldID() As Global.System.Decimal
        Get
            Return _fldID
        End Get
        Set
            If (_fldID <> Value) Then
                OnfldIDChanging(value)
                ReportPropertyChanging("fldID")
                _fldID = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("fldID")
                OnfldIDChanged()
            End If
        End Set
    End Property

    Private _fldID As Global.System.Decimal
    Private Partial Sub OnfldIDChanging(value As Global.System.Decimal)
    End Sub

    Private Partial Sub OnfldIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property fldTitle() As Global.System.String
        Get
            Return _fldTitle
        End Get
        Set
            OnfldTitleChanging(value)
            ReportPropertyChanging("fldTitle")
            _fldTitle = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("fldTitle")
            OnfldTitleChanged()
        End Set
    End Property

    Private _fldTitle As Global.System.String
    Private Partial Sub OnfldTitleChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnfldTitleChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("SealSuiteDBModel", "FK_tblSealUser_tblTitle", "tblUser")>
     Public Property tblUser() As EntityCollection(Of tblUser)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of tblUser)("SealSuiteDBModel.FK_tblSealUser_tblTitle", "tblUser")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of tblUser)("SealSuiteDBModel.FK_tblSealUser_tblTitle", "tblUser", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="SealSuiteDBModel", Name:="tblUser")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class tblUser
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new tblUser object.
    ''' </summary>
    ''' <param name="fldID">Initial value of the fldID property.</param>
    Public Shared Function CreatetblUser(fldID As Global.System.Decimal) As tblUser
        Dim tblUser as tblUser = New tblUser
        tblUser.fldID = fldID
        Return tblUser
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property fldID() As Global.System.Decimal
        Get
            Return _fldID
        End Get
        Set
            If (_fldID <> Value) Then
                OnfldIDChanging(value)
                ReportPropertyChanging("fldID")
                _fldID = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("fldID")
                OnfldIDChanged()
            End If
        End Set
    End Property

    Private _fldID As Global.System.Decimal
    Private Partial Sub OnfldIDChanging(value As Global.System.Decimal)
    End Sub

    Private Partial Sub OnfldIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property fldLastName() As Global.System.String
        Get
            Return _fldLastName
        End Get
        Set
            OnfldLastNameChanging(value)
            ReportPropertyChanging("fldLastName")
            _fldLastName = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("fldLastName")
            OnfldLastNameChanged()
        End Set
    End Property

    Private _fldLastName As Global.System.String
    Private Partial Sub OnfldLastNameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnfldLastNameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property fldFirstName() As Global.System.String
        Get
            Return _fldFirstName
        End Get
        Set
            OnfldFirstNameChanging(value)
            ReportPropertyChanging("fldFirstName")
            _fldFirstName = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("fldFirstName")
            OnfldFirstNameChanged()
        End Set
    End Property

    Private _fldFirstName As Global.System.String
    Private Partial Sub OnfldFirstNameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnfldFirstNameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property fldTitleID() As Nullable(Of Global.System.Decimal)
        Get
            Return _fldTitleID
        End Get
        Set
            OnfldTitleIDChanging(value)
            ReportPropertyChanging("fldTitleID")
            _fldTitleID = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("fldTitleID")
            OnfldTitleIDChanged()
        End Set
    End Property

    Private _fldTitleID As Nullable(Of Global.System.Decimal)
    Private Partial Sub OnfldTitleIDChanging(value As Nullable(Of Global.System.Decimal))
    End Sub

    Private Partial Sub OnfldTitleIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property fldSystemLogin() As Global.System.String
        Get
            Return _fldSystemLogin
        End Get
        Set
            OnfldSystemLoginChanging(value)
            ReportPropertyChanging("fldSystemLogin")
            _fldSystemLogin = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("fldSystemLogin")
            OnfldSystemLoginChanged()
        End Set
    End Property

    Private _fldSystemLogin As Global.System.String
    Private Partial Sub OnfldSystemLoginChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnfldSystemLoginChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property fldSignature() As Global.System.Byte()
        Get
                Return StructuralObject.GetValidValue(_fldSignature)
        End Get
        Set
            OnfldSignatureChanging(value)
            ReportPropertyChanging("fldSignature")
            _fldSignature = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("fldSignature")
            OnfldSignatureChanged()
        End Set
    End Property

    Private _fldSignature As Global.System.Byte()
    Private Partial Sub OnfldSignatureChanging(value As Global.System.Byte())
    End Sub

    Private Partial Sub OnfldSignatureChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property fldProcess() As Nullable(Of Global.System.Boolean)
        Get
            Return _fldProcess
        End Get
        Set
            OnfldProcessChanging(value)
            ReportPropertyChanging("fldProcess")
            _fldProcess = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("fldProcess")
            OnfldProcessChanged()
        End Set
    End Property

    Private _fldProcess As Nullable(Of Global.System.Boolean)
    Private Partial Sub OnfldProcessChanging(value As Nullable(Of Global.System.Boolean))
    End Sub

    Private Partial Sub OnfldProcessChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property fldTest() As Nullable(Of Global.System.Boolean)
        Get
            Return _fldTest
        End Get
        Set
            OnfldTestChanging(value)
            ReportPropertyChanging("fldTest")
            _fldTest = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("fldTest")
            OnfldTestChanged()
        End Set
    End Property

    Private _fldTest As Nullable(Of Global.System.Boolean)
    Private Partial Sub OnfldTestChanging(value As Nullable(Of Global.System.Boolean))
    End Sub

    Private Partial Sub OnfldTestChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property fldIPE() As Nullable(Of Global.System.Boolean)
        Get
            Return _fldIPE
        End Get
        Set
            OnfldIPEChanging(value)
            ReportPropertyChanging("fldIPE")
            _fldIPE = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("fldIPE")
            OnfldIPEChanged()
        End Set
    End Property

    Private _fldIPE As Nullable(Of Global.System.Boolean)
    Private Partial Sub OnfldIPEChanging(value As Nullable(Of Global.System.Boolean))
    End Sub

    Private Partial Sub OnfldIPEChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("SealSuiteDBModel", "FK_tblProcess_UserRole_tblUser", "tblProcess_UserRole")>
     Public Property tblProcess_UserRole() As EntityCollection(Of tblProcess_UserRole)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of tblProcess_UserRole)("SealSuiteDBModel.FK_tblProcess_UserRole_tblUser", "tblProcess_UserRole")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of tblProcess_UserRole)("SealSuiteDBModel.FK_tblProcess_UserRole_tblUser", "tblProcess_UserRole", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("SealSuiteDBModel", "FK_tblSealUserRole_tblSealUser", "tblTest_UserRole")>
     Public Property tblTest_UserRole() As EntityCollection(Of tblTest_UserRole)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of tblTest_UserRole)("SealSuiteDBModel.FK_tblSealUserRole_tblSealUser", "tblTest_UserRole")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of tblTest_UserRole)("SealSuiteDBModel.FK_tblSealUserRole_tblSealUser", "tblTest_UserRole", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("SealSuiteDBModel", "FK_tblSealUser_tblTitle", "tblTitle")>
    Public Property tblTitle() As tblTitle
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of tblTitle)("SealSuiteDBModel.FK_tblSealUser_tblTitle", "tblTitle").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of tblTitle)("SealSuiteDBModel.FK_tblSealUser_tblTitle", "tblTitle").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property tblTitleReference() As EntityReference(Of tblTitle)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of tblTitle)("SealSuiteDBModel.FK_tblSealUser_tblTitle", "tblTitle")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of tblTitle)("SealSuiteDBModel.FK_tblSealUser_tblTitle", "tblTitle", value)
            End If
        End Set
    End Property

    #End Region

End Class

#End Region


