
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.ComponentModel
Imports System.Data.EntityClient
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq
Imports System.Runtime.Serialization
Imports System.Xml.Serialization


<Assembly: EdmSchemaAttribute("a8c0d314-76ca-4fd0-bd50-9ae7a94d59d0")>
#Region "Contexts"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
Public Partial Class SealPart_DDListDBEntities
    Inherits ObjectContext

    #Region "Constructors"

    ''' <summary>
    ''' Initializes a new SealPart_DDListDBEntities object using the connection string found in the 'SealPart_DDListDBEntities' section of the application configuration file.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=SealPart_DDListDBEntities", "SealPart_DDListDBEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new SealPart_DDListDBEntities object.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "SealPart_DDListDBEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new SealPart_DDListDBEntities object.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "SealPart_DDListDBEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    #End Region

    #Region "Partial Methods"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "ObjectSet Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property tblCustList() As ObjectSet(Of tblCustList)
        Get
            If (_tblCustList Is Nothing) Then
                _tblCustList = MyBase.CreateObjectSet(Of tblCustList)("tblCustList")
            End If
            Return _tblCustList
        End Get
    End Property

    Private _tblCustList As ObjectSet(Of tblCustList)

    #End Region

    #Region "AddTo Methods"

    ''' <summary>
    ''' Deprecated Method for adding a new object to the tblCustList EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddTotblCustList(ByVal tblCustList As tblCustList)
        MyBase.AddObject("tblCustList", tblCustList)
    End Sub

    #End Region

End Class

#End Region

#Region "Entities"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="SealPart_DDListDBModel", Name:="tblCustList")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class tblCustList
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new tblCustList object.
    ''' </summary>
    ''' <param name="fldID">Initial value of the fldID property.</param>
    ''' <param name="fldCustList">Initial value of the fldCustList property.</param>
    Public Shared Function CreatetblCustList(fldID As Global.System.Int32, fldCustList As Global.System.String) As tblCustList
        Dim tblCustList as tblCustList = New tblCustList
        tblCustList.fldID = fldID
        tblCustList.fldCustList = fldCustList
        Return tblCustList
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property fldID() As Global.System.Int32
        Get
            Return _fldID
        End Get
        Set
            If (_fldID <> Value) Then
                OnfldIDChanging(value)
                ReportPropertyChanging("fldID")
                _fldID = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("fldID")
                OnfldIDChanged()
            End If
        End Set
    End Property

    Private _fldID As Global.System.Int32
    Private Partial Sub OnfldIDChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnfldIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property fldCustList() As Global.System.String
        Get
            Return _fldCustList
        End Get
        Set
            OnfldCustListChanging(value)
            ReportPropertyChanging("fldCustList")
            _fldCustList = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("fldCustList")
            OnfldCustListChanged()
        End Set
    End Property

    Private _fldCustList As Global.System.String
    Private Partial Sub OnfldCustListChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnfldCustListChanged()
    End Sub

    #End Region

End Class

#End Region


